conky.config = {

    use_xft = true,
    xftalpha = 1,
    override_utf8_locale = true,
    short_units = true,

    update_interval = 5,
    total_run_times = 0,

    own_window = true,
    own_window_type = 'normal',
    own_window_transparent = false,
    own_window_argb_value = 2,
    own_window_argb_visual = true,
    own_window_colour = '000000',
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager',

    double_buffer = true,

    minimum_size = '320 5',
    maximum_width = 345,
    max_text_width = 0,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = true,

    stippled_borders = 5,
    border_inner_margin = 0,
    border_outer_margin = 0,
    border_width = 1,

    default_color = '00FC0D',
    default_shade_color = 'black',
    default_outline_color = 'black',

    alignment = 'top_left',

    gap_x = 1,
    gap_y = 1,

    no_buffers = true,
    uppercase = false,

    top_name_width = 18,
    top_cpu_separate = false,

    lua_load = 'network.lua',
}


conky.text = [[
${font TerminessNerdFontMono-Regular:size= 11}@-- More Infos
@-- Time
|   |-- Now < ${time %a %d. %b %k:%M} >
|   '-- Uptime < $uptime >
|
@-- ${nodename} on < wlan0 >
|   |-- Internal
|   |   |-- IP  < ${addr wlan0} >
|   |   |-- GW  < ${gw_ip} >
|   |   '-- DNS < ${nameserver} >
|   |
|   |-- External
|       |-- IPv4 < ${execi 36000 wget -q -O - checkip.dyndns.org | sed -e 's/[^[:digit:]\|.]//g' | awk -F "." '{print($1"."$2"."$3"."$4)}'} >
|       '-- IPv6 ${font TerminessNerdFontMono-Regular:size= 8} < ${execi 36000 wget -q -O - https://api64.ipify.org} >${font TerminessNerdFontMono-Regular:size= 11}
|
@-- Network
|   |-- Up < ${upspeed wlan0} > / < ${totalup wlan0} k/s >
|   |   '-- < ${upspeedgraph wlan0 11,168 8b2132 fe8608} >
|   |-- Down < ${downspeed wlan0} k/s > / < ${totaldown wlan0} >
|   |   '--- < ${downspeedgraph wlan0 11,168 8b2132 fe8608} >
|   |
|   |-- Devices on the Network
${lua_parse network_devices}
]]
